// src/mockData.js

export const mockUsers = [
  {
    id: "u1",
    name: "Saauce",
    role: "player",
    avatar: "https://picsum.photos/seed/u1/200",
    isVerified: true,
    position: "Meia",
    walletBalance: 42.5,
    stats: { goals: 12, assists: 6, gamesPlayed: 18 },
    unlockedAchievementIds: ["a1", "a2"],
  },
  {
    id: "u2",
    name: "Carlos Silva",
    role: "player",
    avatar: "https://picsum.photos/seed/u2/200",
    isVerified: false,
    position: "Atacante",
    walletBalance: 10.0,
    stats: { goals: 20, assists: 4, gamesPlayed: 22 },
    unlockedAchievementIds: ["a1", "a3"],
  },
  {
    id: "u3",
    name: "Bruno Souza",
    role: "player",
    avatar: "https://picsum.photos/seed/u3/200",
    isVerified: true,
    position: "Zagueiro",
    walletBalance: 0.0,
    stats: { goals: 2, assists: 1, gamesPlayed: 10 },
    unlockedAchievementIds: [],
  },
  {
    id: "u4",
    name: "Diego Lima",
    role: "player",
    avatar: "https://picsum.photos/seed/u4/200",
    isVerified: false,
    position: "Goleiro",
    walletBalance: 5.75,
    stats: { goals: 0, assists: 0, gamesPlayed: 8 },
    unlockedAchievementIds: ["a2"],
  },
];

export const achievements = [
  {
    id: "a1",
    title: "Artilheiro",
    description: "Goleador nato.",
    objective: "Marcar 10 gols",
    category: "goals",
    targetValue: 10,
    icon: "⚽",
  },
  {
    id: "a2",
    title: "Maestro",
    description: "Passe que vira gol.",
    objective: "Dar 5 assistências",
    category: "assists",
    targetValue: 5,
    icon: "🎯",
  },
  {
    id: "a3",
    title: "Veterano",
    description: "Constância é tudo.",
    objective: "Jogar 20 partidas",
    category: "games",
    targetValue: 20,
    icon: "🏅",
  },
  {
    id: "a4",
    title: "Craque da Resenha",
    description: "Tá sempre presente na pelada.",
    objective: "Participar de 5 peladas",
    category: "other",
    targetValue: 5,
    icon: "🔥",
  },
];
